### ISSUE TITLE
search api went away

### ISSUE THREAD

**Issue by fionnb** [TechShreyash/AniDL#4]
https://api.anime-dex.workers.dev is gone - maybe temporarily? I don't know. But before that, it also was overloaded temporarily. 

I would suggest to check if the search api actually works, like this:

```
def gogo_search(self, query):
  data = requests.get(f"{self.base}/search/{query}")
  try:
    data = data.json()
  except:
    print("search error: HTTP/%s - try again later" % data.status_code)
    return []
  return data["results"]
```

**Comment by TechShreyash** [comment]
To use the animedex api you need to deploy your own instance, repo https://github.com/TechShreyash/AnimeDexApi

The public api api.anime-dex.workers.dev is no longer hosted by me


> I would suggest to check if the search api actually works, like this:

Yes it will, though i suggest replacing blank spaces with + sign
Like horimiya dub => horimiya+dub
